apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vrising.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vrising.labels" . | nindent 4 }}
data:
  ServerHostSettings.json: |
    {{- .Values.serverHostSettings | toPrettyJson | nindent 4 }}
  ServerGameSettings.json: |
    {{- .Values.serverGameSettings | toPrettyJson | nindent 4 }}
  adminlist.txt: |
    {{- range .Values.adminList }}
    {{ . }}
    {{- end }}
